###########################################################################################################################
#                                          Identification of spanning motifs - 5                                          #
###########################################################################################################################

# Importing the required modules
import os

# List of nucleotides and amino acids.
NT = ['-  A', '-  U', '-  G', '-  C']
AA = ['-GLY', '-ALA', '-SER', '-THR', '-CYS', '-VAL', '-LEU', '-ILE', '-MET',
      '-PRO', '-PHE', '-TYR', '-TRP', '-ASP', '-GLU', '-ASN', '-GLN', '-HIS', '-LYS', '-ARG']

# Read nucleotide-mediated spanning motif generated by script '3_Remove_fasle_spanning_motifs.py'
file = open('NT_spanningmotifs.txt', 'r')
out = []
i = -1
start_line_plus_first_line = []
end_line = []
my_dict = {"pdb":[],"val":[]}
pdb = []
data = file.readlines()
for lines in data: 
    i += 1
    if lines.find('PDB:') >= 0:
        start_line_plus_first_line.append(i)
    elif lines.find('.....................................') >= 0:
        end_line.append(i)
print(start_line_plus_first_line)
print(end_line)

for n in range(len(start_line_plus_first_line)):
    for m in range(len(end_line)):
        if n == m:
            my_dict["pdb"].append(data[start_line_plus_first_line[n]])
            my_dict["val"].append(data[start_line_plus_first_line[n]+1:end_line[m]])

for l in range(len(my_dict['val'])):   
    for lines in my_dict['val'][l]:
        aa =  []
        nt =  []
        if '[' in lines:
            inter = lines.split('---')
            for i in inter:
                if i.strip()[:9] not in nt: nt.append(i.strip()[:9])
                if i.strip()[14:23] not in aa: aa.append(i.strip()[14:23])
            t = ('A' + str(len(aa)) + 'N' + str(len(nt)))
        
        filename = t + '.txt'
        path = os.getcwd()
        directory = os.listdir(path)  # specify folder path.
        if filename in directory: 
            out_files = open(filename, 'r')
            if my_dict['pdb'][l] not in out_files: 
                print(my_dict['pdb'][l].strip(), file=open(filename, "a"))
    
        else:
            print(my_dict['pdb'][l].strip(), file=open(filename, "a"))
        print(lines.strip(), file=open(filename, "a"))
        
print('******************************************', file=open('A2N1.txt', "a"))